name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - name: 'standalone'
            self-contained: true
          - name: 'framework-dependent'
            self-contained: false

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build and Publish
      run: |
        dotnet publish \
          -c Release \
          -r win-x64 \
          --self-contained ${{ matrix.configuration.self-contained }} \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          -p:EnableCompressionInSingleFile=true \
          -o publish/${{ matrix.configuration.name }}

    - name: Create Release Asset
      run: |
        cd publish/${{ matrix.configuration.name }}
        7z a -tzip ../${{ matrix.configuration.name }}.zip WindowsInputHelper.exe

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: publish/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}